### ISSUE TITLE
"How to install MikroTik CHR on Hetzner Cloud"-Issue

### ISSUE THREAD

**Issue by philippkayser** [hetzneronline/community-content#396] opened 2021-11-30 13:44 UTC
## Problem
Following the content provided in the tutorial  the server will not boot the new image after a reboot.
![image](https://user-images.githubusercontent.com/41049458/144058282-71aa462a-3ace-4bbd-a490-9097cd8e1960.png)

## Suggested Fix

**Comment by rook59** [comment] 2021-12-13 14:18
You are the second person reporting this issue, see https://github.com/hetzneronline/community-content/issues/394#issuecomment-982412941

I cannot reproduce it. Can you please copy & paste the **exact** steps you used for me?

**Comment by rook59** [comment] 2022-02-25 12:09
Closing this because no further information provided. Please let me know if you continue to have problems and provide reproducible steps.

**Closed by rook59** 2022-02-25 12:09 UTC
Labels: bug, question
