### ISSUE TITLE
How to install Arch Linux on a Hetzner Cloud server

### ISSUE THREAD

**Issue by rfoerthe** [hetzneronline/community-content#984] opened 2024-11-01 15:05 UTC
## Problem
I think the command 'genfstab -U /mnt >> /etc/fstab' updates the wrong fstab file (the one of the bootstrap env).
## Suggested Fix
Run the corrected command after pacstrap in step 2:
genfstab -U /mnt >> /mnt/etc/fstab

**Comment by wpdevelopment11** [comment] 2024-11-01 18:39
Duplicate of #956

**Closed** 2024-11-06 12:28 UTC
