### ISSUE TITLE
Install Rancher on a Cloud Server (Single Node)

### ISSUE THREAD

**Issue by fatih-akin** [hetzneronline/community-content#543] opened 2023-01-06 21:33 UTC
I am getting error below. So rancher can not download from  [https://storage.googleapis.com/hcloud-rancher-v2-ui-driver/component.js ](url) GCP

`<Error>`
`<Code>UserProjectAccountProblem</Code>`
`<Message>The project to be billed is associated with a closed billing account.</Message>`
`<Details>The billing account for the owning project is disabled in state closed</Details>`
`</Error>`

**Comment by zmbcgn** [comment] 2023-01-24 13:13
Seems like a temporary problem with the Google account. As of today, the link is working.

**Comment by zmbcgn** [comment] 2023-01-24 13:14
Duplicate of #538 .

**Comment by biberairport** [comment] 2023-01-31 10:07
Thank you for the report, since it was a temporary problem we will close this now.

**Closed by biberairport** 2023-01-31 10:07 UTC
