### ISSUE TITLE
Assign IPs to docker containers using Hetzner Subnet

### ISSUE THREAD

**Issue by MrBenFTW** [hetzneronline/community-content#285] opened 2021-01-14 20:55 UTC
I have been trying to Assign IPs to my docker containers using my /28 Hetzner subnet on my dedicated server for a few weeks now and I cannot for the life of me figure out how to get it to work.

I've resorted to using VMs instead plus a router VM. But I would really like to use docker. 

I had it working at some point but although the containers could be accessed with the public ip, traffic out of the containers would appear to be from the host server.

**Comment by rook59** [comment] 2021-01-26 12:32
You could try to ask this question in our Forum https://forum.hetzner.com with some more details and configuration examples. Maybe someone can help you with your issue there. The issue is out of scope here.

**Closed by rook59** 2021-01-26 12:32 UTC
